In [1]:
import numpy as np
from sympy import Matrix
from sympy import *


#1.Create and transform vectors and matrices and transpose them:

#Creating a Vector
vector = np.matrix([7, 3, 2])
print("Vector is:\n", vector )


# Transpose the Vector
print("\nTRANSPOSE THE VECTOR\n")

vector_transpose = vector.T
print("Transpose of The Given Vector is:\n", vector_transpose)

# Creating a Matrix
mat1 = np.matrix([[6, 7, 9], [5, 7, 1], [2, 0, 4]])
print("Matrix is:\n",mat1)

# Transpose of Matrix
print("\nTRANSPOSE THE MATRIX\n")
matrix_transpose = np.transpose(mat1)
print("Transpose of The Given  Matrix is:\n", matrix_transpose)

# Conjugate Transpose of The Matrix

print("\n CONJUGATE TRANSPOSE THE MATRIX \n")
matrix_conjugate_transpose = np.conj(mat1)
print("Conjugate Transpose of The Given matrix is:\n", matrix_conjugate_transpose)

Vector is:
 [[9 8 7]]

TRANSPOSE THE VECTOR

Transpose of The Given Vector is:
 [[9]
 [8]
 [7]]
Matrix is:
 [[6 7 9]
 [5 7 1]
 [2 0 4]]

TRANSPOSE THE MATRIX

Transpose of The Given  Matrix is:
 [[6 5 2]
 [7 7 0]
 [9 1 4]]

 CONJUGATE TRANSPOSE THE MATRIX 

Conjugate Transpose of The Given matrix is:
 [[6 7 9]
 [5 7 1]
 [2 0 4]]


In [2]:
import numpy as np
from sympy import Matrix
from sympy import *

#2.Generate The Matrix into Echelon Form and Find its Rank.

# Creating a Matrix

matrix= Matrix([[3, 7, 9,],[5, 2, 1,],[-2, -9, 8]])

print("Matrix is: \n ")
print(np.array(matrix).astype(np.float64))

#Finding Reduced Row Echelon Form of The Matrix

def echelon_form(matrix):
    print("\n ROW REDUCED ECHELON FORM OF THE MATRIX\n")
    print("Reduced Row Echelon Form is: \n ")
    return (np.array(matrix.rref()[0]).astype(np.float64))

print(echelon_form(matrix))

#Finding Rank of The Matrix

def rank_matrix(matrix):
    print("\n RANK OF THE MATRIX\n")
    print("Rank of matrix is: \n ")
    return np.linalg.matrix_rank(np.array(matrix).astype(np.float64))

print(rank_matrix(matrix))

Matrix is: 
 
[[ 3.  7.  9.]
 [ 5.  2.  1.]
 [-2. -9.  8.]]

 ROW REDUCED ECHELON FORM OF THE MATRIX

Reduced Row Echelon Form is: 
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 RANK OF THE MATRIX

Rank of matrix is: 
 
3


In [3]:
import numpy as np

#3.Find Cofactors, Determinant, Adjoint and Inverse of a Matrix.

# Creating a Matrix
matrix = np.array([[5,3,4], [3,1,-2], [-2,0,-3]])
print("Matrix is: \n", matrix)

#Determinant of a Matrix:
determinant_matrix=np.linalg.det(matrix)
print("\n Determinant of The Given Matrix is:\n" , determinant_matrix)

#Inverse of a Matrix:
inverse_matrix=np.linalg.inv(matrix)
print("\n Inverse of The Given Matrix is: \n",inverse_matrix)

#Adjoint of a matrix:
adjoint_matrix = inverse_matrix*determinant_matrix
print("\n Adjoint of The Given Matrix is: \n" , adjoint_matrix)

#Cofactor of a matrix:
cofactor_matrix = np.transpose(adjoint_matrix)
print("\n Cofactor of The Given Matrix is: \n", cofactor_matrix)

Matrix is: 
 [[ 5  3  4]
 [ 3  1 -2]
 [-2  0 -3]]

 Determinant of The Given Matrix is:
 32.0

 Inverse of The Given Matrix is: 
 [[-0.09375  0.28125 -0.3125 ]
 [ 0.40625 -0.21875  0.6875 ]
 [ 0.0625  -0.1875  -0.125  ]]

 Adjoint of The Given Matrix is: 
 [[ -3.   9. -10.]
 [ 13.  -7.  22.]
 [  2.  -6.  -4.]]

 Cofactor of The Given Matrix is: 
 [[ -3.  13.   2.]
 [  9.  -7.  -6.]
 [-10.  22.  -4.]]


In [6]:
import numpy as np

print("\n -----GAUSS ELIMINATION METHOD-----\n")

A = np.matrix(input("Write elements separated by spaces and separate rows with semi-colon: \n"))
print("Matrix 1 is: \n", A)
#Example_A = 1 1 1;2 -3 4;3 4 5

B = np.matrix(input("\n Write elements separated by semi-colon: \n"))
print("Matrix 2 is: \n", B)  
#Example_B = 9;13;40

# Applying Gauss Elimination

# Solve the system of linear equations using Gaussian elimination method in NumPy
x = np.linalg.solve(A, B)
#Augmented_A:B = 1 1 1 9;2 -3 4 13;3 4 5 40

# Print the solution vector
print("\n Solution vector: \n")
print(x)
#Solution_X = 1;3;5



 -----GAUSS ELIMINATION METHOD-----

Write elements separated by spaces and separate rows with semi-colon: 
 1 1 1;2 -3 4;3 4 5
Matrix 1 is: 
 [[ 1  1  1]
 [ 2 -3  4]
 [ 3  4  5]]

 Write elements separated by semi-colon: 
5;8;9
Matrix 2 is: 
 [[5]
 [8]
 [9]]

 Solution vector: 

[[ 8.33333333]
 [-0.66666667]
 [-2.66666667]]


In [8]:
import numpy as np
print("\n-----GAUSS-JORDAN METHOD-----\n")

A = np.matrix(input("Write elements separated by spaces and separate rows with semi-colon: "))
print("Matrix A is \n: ", A, "\n")
#Example_A = 1 1 1;2 -3 4;3 4 5

B = np.matrix(input("\n Write elements separated by semi-colon: "))
print("Matrix B is: \n", B, "\n") 
#Example_B = 9;13;40

#Computing the inverse of A using numpy.linalg.inv()
A_inv = np.linalg.inv(A)
print("\n Inverse of Matrix A is: \n {}".format(A_inv))

#Computing the solution vector x using the Gauss-Jordan method
x = np.dot(A_inv, B)

# Printing the solution vector
print("\n Solution vector: \n")
print(x)
#Solution_X = 1;3;5


-----GAUSS-JORDAN METHOD-----

Write elements separated by spaces and separate rows with semi-colon: 6 9 6; 5 3 7; 1 2 8
Matrix A is 
:  [[6 9 6]
 [5 3 7]
 [1 2 8]] 


 Write elements separated by semi-colon: 5;7;8
Matrix B is: 
 [[5]
 [7]
 [8]] 


 Inverse of Matrix A is: 
 [[-0.05128205  0.30769231 -0.23076923]
 [ 0.16923077 -0.21538462  0.06153846]
 [-0.03589744  0.01538462  0.13846154]]

 Solution vector: 

[[ 0.05128205]
 [-0.16923077]
 [ 1.03589744]]


In [18]:
import numpy as np
from sympy import Matrix
from sympy import *

#6.Generate Basis of Column Space, Null Space, Row Space and Left Null Space of a Matrix Space

matrix = Matrix([[1, 2, -1], [-2, -4, 2], [3, 6, -3]])
print("Matrix is:\n", matrix)

#To Find The Column Space of The Matrix:

print("\n COLUMN SPACE OF THE MATRIX\n")
matrix_columnspace=matrix.columnspace()
print("\nThe Column Space of the Matrix is:\n",matrix_columnspace, "\n")

#To Find The Row Space of The Matrix:

print("\n ROW SPACE OF THE MATRIX\n")
matrix_rowspace=matrix.rowspace()
print("\nThe Row Space of the Matrix is:\n",matrix_rowspace)

#To Find The Null Space of The Matrix:

print("\n NULL SPACE OF THE MATRIX\n")
matrix_nullspace=matrix.nullspace()
print("\nThe Null Space of the Matrix is:\n",matrix_nullspace)


#To Find The Left Null Space of The Matrix:

print("\n LEFT NULL SPACE OF THE MATRIX\n")
AB = matrix.T
matrix_leftnullspace = AB.nullspace()
print("\nMatrix Transpose is :\n ")
print(AB)

print("\nLeft Null Space of the Matrix is: \n")
print(matrix_leftnullspace)  

Matrix is:
 Matrix([[1, 2, -1], [-2, -4, 2], [3, 6, -3]])

 COLUMN SPACE OF THE MATRIX


The Column Space of the Matrix is:
 [Matrix([
[ 1],
[-2],
[ 3]])] 


 ROW SPACE OF THE MATRIX


The Row Space of the Matrix is:
 [Matrix([[1, 2, -1]])]

 NULL SPACE OF THE MATRIX


The Null Space of the Matrix is:
 [Matrix([
[-2],
[ 1],
[ 0]]), Matrix([
[1],
[0],
[1]])]

 LEFT NULL SPACE OF THE MATRIX


Matrix Transpose is :
 
Matrix([[1, -2, 3], [2, -4, 6], [-1, 2, -3]])

Left Null Space of the Matrix is: 

[Matrix([
[2],
[1],
[0]]), Matrix([
[-3],
[ 0],
[ 1]])]


In [9]:
import numpy as np

def check_linear_dependence(vectors):
    # Create a matrix from the vectors
    matrix = np.array(vectors).T
    
    rank = np.linalg.matrix_rank(matrix)
    # Check if the columns are linearly dependent
    if rank < matrix.shape[1]:
        print("The columns of the matrix are linearly dependent.\n")
    else:
        print("The columns of the matrix are linearly independent.\n")

# Example usage
vectors = [[1, 2, 3], [2, 4, 6], [3, 5, 7]]
check_linear_dependence(vectors)  # The vectors are linearly dependent.

vectors = [[1, 2, 3]]
check_linear_dependence(vectors)  # The vectors are linearly independent.

# define the vectors as numpy arrays
v1 = np.array([[1, 2, 3], [2, -4, -9], [5, 9, -7]])
v2 = np.array([[4, 5, 6], [1, 4, 6], [-9, -1, 0]])

# define the coefficients
a = int(input("Enter a coefficient for v1: "))
b = int(input("Enter another coefficient for v2: "))

# calculate the linear combination
linear_combination = a*v1 + b*v2

print("Linear combination of ({} \n and \n {}) is: \n \n".format(v1, v2), linear_combination)

The columns of the matrix are linearly dependent.

The columns of the matrix are linearly independent.

Enter a coefficient for v1: 2
Enter another coefficient for v2: 3
Linear combination of ([[ 1  2  3]
 [ 2 -4 -9]
 [ 5  9 -7]] 
 and 
 [[ 4  5  6]
 [ 1  4  6]
 [-9 -1  0]]) is: 
 
 [[ 14  19  24]
 [  7   4   0]
 [-17  15 -14]]


In [10]:
import numpy as np
#8. Finding the orthonormal basis of a given vector space using
#Gram-Schmidt Orthogonalization process.


#Declaring sub-spaces:
v1 = [1,1,1,1]
print("Sub-space v1 is: ", v1)
v2 = [1,1,-1,-1]
print("Sub-space v2 is: ", v2)
v3 = [0,-1,2,1]
print("Sub-space v3 is: ", v3, "\n")

#Declaring Vector-space:
v = np.array([v1,v2,v3])
print("Vector-space V is: \n", v, "\n")

#Converting sub-spaces to their orthonormal form:
u1 = v1/np.linalg.norm(v1)
print("Orthonormal sub-space of v1 is: ", u1)

e2 = v2 - np.dot(np.dot(u1,v2),u1)
u2 = e2/np.linalg.norm(e2)
print("Orthonormal sub-space of v2 is: ", u2)

e3 = v3 - (np.dot(np.dot(u1,v3),u1) + np.dot(np.dot(u2,v3),u2))
u3 = e3/np.linalg.norm(e3)
print("Orthonormal sub-space of v3 is: ", u3, "\n")

#Testing for orthonormality: Dot product of any 2 vetor 
#should be zero and they should be unit vector. 
print("Testing if the generated vectors are orthonormal: \n")
test1 = np.dot(u1,u2)
print("Dot product of u1 & u2 is {} and norm of u is {}".format(test1, np.linalg.norm(u1)))
test2 = np.dot(u1,u3)
print("Dot product of u1 & u3 is {} and norm of u is {}".format(test2, np.linalg.norm(u2)))
test3 = np.dot(u2,u3)
print("Dot product of u2 & u3 is {} and norm of u is {}".format(test3, np.linalg.norm(u3)), "\n")

#Finally, outputing the generated Orthonormal Vector-space:
u = np.array([u1,u2,u3])
print("Orthonormalised Vector-space V is: \n", u)

Sub-space v1 is:  [1, 1, 1, 1]
Sub-space v2 is:  [1, 1, -1, -1]
Sub-space v3 is:  [0, -1, 2, 1] 

Vector-space V is: 
 [[ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 0 -1  2  1]] 

Orthonormal sub-space of v1 is:  [0.5 0.5 0.5 0.5]
Orthonormal sub-space of v2 is:  [ 0.5  0.5 -0.5 -0.5]
Orthonormal sub-space of v3 is:  [ 0.5 -0.5  0.5 -0.5] 

Testing if the generated vectors are orthonormal: 

Dot product of u1 & u2 is 0.0 and norm of u is 1.0
Dot product of u1 & u3 is 0.0 and norm of u is 1.0
Dot product of u2 & u3 is 0.0 and norm of u is 1.0 

Orthonormalised Vector-space V is: 
 [[ 0.5  0.5  0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5 -0.5]]


In [11]:
import numpy as np
# Defining a matrix
A = np.array([[1, 2], [3, 4]])

# Finding the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A is: \n", A)
print("\n Eigenvalues are: \n", eigenvalues)
print("\n Eigenvectors are: \n", eigenvectors)

diag_eigval = np.diag(eigenvalues)
p_inv = np.linalg.inv(eigenvectors)
p = eigenvectors
    
# Checking if the matrix is diagonalizable
if np.allclose(diag_eigval, np.dot(p_inv, np.dot(A, p))):
    print("\n The matrix is diagonalizable.")
else:
    print("\n The matrix is not diagonalizable. \n")
    
# Checking if the given matrix satisfies CHT
B = np.array([[2, -1, 0], [1, 4, -1], [0, 1, 3]])
bp = np.poly(B)
print("\n Characteristic polynomial of B: ", bp, "\n")
subs_b = np.dot(np.dot(B, B), B) -9*(np.dot(B, B)) +28*B -29*np.eye(3)

#substituting the matrix B into the characteristic polynomial bp 
# and checking if the resulting expression is equivalent to zero.

if np.allclose(subs_b, np.zeros((3, 3))):
    print("The matrix B satisfies Cayley-Hamilton Theorem.")
else:
    print("The matrix B doesn't satisfy Cayley-Hamilton Theorem.")

Matrix A is: 
 [[1 2]
 [3 4]]

 Eigenvalues are: 
 [-0.37228132  5.37228132]

 Eigenvectors are: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

 The matrix is diagonalizable.

 Characteristic polynomial of B:  [  1.  -9.  28. -29.] 

The matrix B satisfies Cayley-Hamilton Theorem.


In [12]:
import numpy as np

# Define the message to be encoded as a column vector
message = np.array([[1], [2], [3]])

# Define the encoding matrix (must be non-singular)
encoding_matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Encode the message by multiplying it with the encoding matrix
encoded_message = np.dot(encoding_matrix, message)

# Calculate the inverse of the encoding matrix
inv_encoding_matrix = np.linalg.inv(encoding_matrix)

# Decode the message by multiplying the encoded message with the inverse of the encoding matrix
decoded_message = np.dot(inv_encoding_matrix, encoded_message)

# Print the encoded message
print("Encoded message: \n")
print(encoded_message)

# Print the decoded message
print("\n Decoded message: \n")
print(decoded_message)

Encoded message: 

[[14]
 [14]
 [17]]

 Decoded message: 

[[1.]
 [2.]
 [3.]]


In [13]:
import sympy

# Define the symbols x, y, and z
x, y, z = sympy.symbols('x y z')

# Define the scalar field f
f = x**2 + 2*y**3*z - 5*z

# Compute the gradient of f
grad_f = [sympy.diff(f, x), sympy.diff(f, y), sympy.diff(f, z)]

# Print the gradient of f
print(grad_f)

[2*x, 6*y**2*z, 2*y**3 - 5]


In [14]:
import numpy as np
import sympy
#12.>Compute Divergence of a vector field

print("\n DIVERGENCE  OF THE MATRIX\n")

def divergence(F):
    # Computing the partial derivatives of the vector field components
    dPdx = sympy.diff(F[0], x)
    dQdy = sympy.diff(F[1], y)
    dRdz = sympy.diff(F[2], z)
    
    #Computing the divergence of the vector field
    divF = dPdx + dQdy + dRdz
    return divF
x, y, z = sympy.symbols('x y z')
F = sympy.Matrix([(x**2)*z, (-2)*(y**3)*(z**2), x*(y**2)*z])

# Computing the divergence of F
divF = divergence(F)

print("The divergence of the vector field {} is: \n".format(F))
print(divF.simplify())


 DIVERGENCE  OF THE MATRIX

The divergence of the vector field Matrix([[x**2*z], [-2*y**3*z**2], [x*y**2*z]]) is: 

x*y**2 + 2*x*z - 6*y**2*z**2


In [16]:
import sympy as sp
print("\n CURL OF THE MATRIX\n")

# Define the symbols
x, y, z = sp.symbols('x y z')

# Define the vector field
A = sp.Matrix([x*z**3, -2*x**2*y*z, 2*y*z**4])

# Compute the curl of the vector field
curl_A = sp.Matrix([sp.diff(A[2], y) - sp.diff(A[1], z),
                    sp.diff(A[0], z) - sp.diff(A[2], x),
                    sp.diff(A[1], x) - sp.diff(A[0], y)])

curl_A.simplify()
print("The curl of the vector field {} is: \n".format(A))
print(curl_A)


 CURL OF THE MATRIX

The curl of the vector field Matrix([[x*z**3], [-2*x**2*y*z], [2*y*z**4]]) is: 

Matrix([[2*x**2*y + 2*z**4], [3*x*z**2], [-4*x*y*z]])
